package tests

// Edit if desired. Code generated by "fzgen github.com/lc/secretz/lib".

import (
	"testing"

	"github.com/lc/secretz/lib"
)

func Fuzz_CreateOrg(f *testing.F) {
	f.Fuzz(func(t *testing.T, dir string) {
		lib.CreateOrg(dir)
	})
}

func Fuzz_CreateOutputDir(f *testing.F) {
	f.Fuzz(func(t *testing.T, dir string) {
		lib.CreateOutputDir(dir)
	})
}

func Fuzz_Exists(f *testing.F) {
	f.Fuzz(func(t *testing.T, loc string) {
		lib.Exists(loc)
	})
}

func Fuzz_OrgMembers(f *testing.F) {
	f.Fuzz(func(t *testing.T, t1 string) {
		lib.OrgMembers(t1)
	})
}

func Fuzz_QueryApi(f *testing.F) {
	f.Fuzz(func(t *testing.T, t1 string) {
		lib.QueryApi(t1)
	})
}

func Fuzz_SetAPIKey(f *testing.F) {
	f.Fuzz(func(t *testing.T, key string) {
		lib.SetAPIKey(key)
	})
}
