package tests

// Edit if desired. Code generated by "fzgen github.com/kataras/go-serializer/markdown".

import (
	"testing"

	"github.com/kataras/go-serializer/markdown"
	"github.com/thepudds/fzgen/fuzzer"
)

// skipping Fuzz_Serializer_Serialize because parameters include func, chan, or unsupported interface: interface{}

func Fuzz_Markdown_Config_Merge(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var cfg []markdown.Config
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&cfg)

		c := markdown.DefaultConfig()
		c.Merge(cfg)
	})
}

func Fuzz_Markdown_Config_MergeSingle(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var cfg markdown.Config
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&cfg)

		c := markdown.DefaultConfig()
		c.MergeSingle(cfg)
	})
}

func Fuzz_Markdown_New(f *testing.F) {
	f.Fuzz(func(t *testing.T, data []byte) {
		var cfg []markdown.Config
		fz := fuzzer.NewFuzzer(data)
		fz.Fill(&cfg)

		markdown.New(cfg...)
	})
}
