// Code generated by mockery v2.53.0. DO NOT EDIT.

package serializer

import mock "github.com/stretchr/testify/mock"

// MockSerializer is an autogenerated mock type for the Serializer type
type MockSerializer struct {
	mock.Mock
}

type MockSerializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSerializer) EXPECT() *MockSerializer_Expecter {
	return &MockSerializer_Expecter{mock: &_m.Mock}
}

// Serialize provides a mock function with given fields: _a0, _a1
func (_m *MockSerializer) Serialize(_a0 interface{}, _a1 ...map[string]interface{}) ([]byte, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, ...map[string]interface{}) ([]byte, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, ...map[string]interface{}) []byte); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, ...map[string]interface{}) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSerializer_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type MockSerializer_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - _a0 interface{}
//   - _a1 ...map[string]interface{}
func (_e *MockSerializer_Expecter) Serialize(_a0 interface{}, _a1 ...interface{}) *MockSerializer_Serialize_Call {
	return &MockSerializer_Serialize_Call{Call: _e.mock.On("Serialize",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockSerializer_Serialize_Call) Run(run func(_a0 interface{}, _a1 ...map[string]interface{})) *MockSerializer_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]map[string]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(map[string]interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MockSerializer_Serialize_Call) Return(_a0 []byte, _a1 error) *MockSerializer_Serialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSerializer_Serialize_Call) RunAndReturn(run func(interface{}, ...map[string]interface{}) ([]byte, error)) *MockSerializer_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSerializer creates a new instance of MockSerializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSerializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSerializer {
	mock := &MockSerializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
