// Code generated by mockery v2.53.0. DO NOT EDIT.

package pretty

import mock "github.com/stretchr/testify/mock"

// MockLogfer is an autogenerated mock type for the Logfer type
type MockLogfer struct {
	mock.Mock
}

type MockLogfer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogfer) EXPECT() *MockLogfer_Expecter {
	return &MockLogfer_Expecter{mock: &_m.Mock}
}

// Logf provides a mock function with given fields: format, a
func (_m *MockLogfer) Logf(format string, a ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, a...)
	_m.Called(_ca...)
}

// MockLogfer_Logf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logf'
type MockLogfer_Logf_Call struct {
	*mock.Call
}

// Logf is a helper method to define mock.On call
//   - format string
//   - a ...interface{}
func (_e *MockLogfer_Expecter) Logf(format interface{}, a ...interface{}) *MockLogfer_Logf_Call {
	return &MockLogfer_Logf_Call{Call: _e.mock.On("Logf",
		append([]interface{}{format}, a...)...)}
}

func (_c *MockLogfer_Logf_Call) Run(run func(format string, a ...interface{})) *MockLogfer_Logf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockLogfer_Logf_Call) Return() *MockLogfer_Logf_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogfer_Logf_Call) RunAndReturn(run func(string, ...interface{})) *MockLogfer_Logf_Call {
	_c.Run(run)
	return _c
}

// NewMockLogfer creates a new instance of MockLogfer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogfer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogfer {
	mock := &MockLogfer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
