// Code generated by mockery v2.51.1. DO NOT EDIT.

package viper

import (
	viper "github.com/spf13/viper"
	mock "github.com/stretchr/testify/mock"
)

// MockOption is an autogenerated mock type for the Option type
type MockOption struct {
	mock.Mock
}

type MockOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOption) EXPECT() *MockOption_Expecter {
	return &MockOption_Expecter{mock: &_m.Mock}
}

// apply provides a mock function with given fields: v
func (_m *MockOption) apply(v *viper.Viper) {
	_m.Called(v)
}

// MockOption_apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'apply'
type MockOption_apply_Call struct {
	*mock.Call
}

// apply is a helper method to define mock.On call
//   - v *viper.Viper
func (_e *MockOption_Expecter) apply(v interface{}) *MockOption_apply_Call {
	return &MockOption_apply_Call{Call: _e.mock.On("apply", v)}
}

func (_c *MockOption_apply_Call) Run(run func(v *viper.Viper)) *MockOption_apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*viper.Viper))
	})
	return _c
}

func (_c *MockOption_apply_Call) Return() *MockOption_apply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOption_apply_Call) RunAndReturn(run func(*viper.Viper)) *MockOption_apply_Call {
	_c.Run(run)
	return _c
}

// NewMockOption creates a new instance of MockOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOption {
	mock := &MockOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
