// Code generated by mockery v2.51.1. DO NOT EDIT.

package zerolog

import (
	zerolog "github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
)

// MockLevelWriter is an autogenerated mock type for the LevelWriter type
type MockLevelWriter struct {
	mock.Mock
}

type MockLevelWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLevelWriter) EXPECT() *MockLevelWriter_Expecter {
	return &MockLevelWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: p
func (_m *MockLevelWriter) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLevelWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockLevelWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *MockLevelWriter_Expecter) Write(p interface{}) *MockLevelWriter_Write_Call {
	return &MockLevelWriter_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockLevelWriter_Write_Call) Run(run func(p []byte)) *MockLevelWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockLevelWriter_Write_Call) Return(n int, err error) *MockLevelWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLevelWriter_Write_Call) RunAndReturn(run func([]byte) (int, error)) *MockLevelWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}

// WriteLevel provides a mock function with given fields: level, p
func (_m *MockLevelWriter) WriteLevel(level zerolog.Level, p []byte) (int, error) {
	ret := _m.Called(level, p)

	if len(ret) == 0 {
		panic("no return value specified for WriteLevel")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(zerolog.Level, []byte) (int, error)); ok {
		return rf(level, p)
	}
	if rf, ok := ret.Get(0).(func(zerolog.Level, []byte) int); ok {
		r0 = rf(level, p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(zerolog.Level, []byte) error); ok {
		r1 = rf(level, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLevelWriter_WriteLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteLevel'
type MockLevelWriter_WriteLevel_Call struct {
	*mock.Call
}

// WriteLevel is a helper method to define mock.On call
//   - level zerolog.Level
//   - p []byte
func (_e *MockLevelWriter_Expecter) WriteLevel(level interface{}, p interface{}) *MockLevelWriter_WriteLevel_Call {
	return &MockLevelWriter_WriteLevel_Call{Call: _e.mock.On("WriteLevel", level, p)}
}

func (_c *MockLevelWriter_WriteLevel_Call) Run(run func(level zerolog.Level, p []byte)) *MockLevelWriter_WriteLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(zerolog.Level), args[1].([]byte))
	})
	return _c
}

func (_c *MockLevelWriter_WriteLevel_Call) Return(n int, err error) *MockLevelWriter_WriteLevel_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockLevelWriter_WriteLevel_Call) RunAndReturn(run func(zerolog.Level, []byte) (int, error)) *MockLevelWriter_WriteLevel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLevelWriter creates a new instance of MockLevelWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLevelWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLevelWriter {
	mock := &MockLevelWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
